export { NavBar } from "./NavBar/NavBar";
export { Footer } from "./Footer/Footer";
export { Slider } from "./Slider/Slider";
export { FeaturedProducts } from "./FeaturedProducts/FeaturedProducts";
export { Card } from "./Card/Card";
export { Categories } from "./Categories/Categories";
export { Contact } from "./Contact/Contact";
export { ListProducts } from "./ListProducts/ListProducts";
export { Cart } from "./Cart/Cart";
